### ISSUE TITLE
Crash when adding a torrent

### ISSUE THREAD

**Issue by lenormf** [rndusr/stig#135]
Hi,

Running v0.10.1a0 installed from Pypi, I added a magnet link using `:add` and the following crash occurred:

```
Traceback (most recent call last):
  File "/usr/bin/stig", line 10, in <module>
    sys.exit(run())
  File "/usr/lib/python3.8/site-packages/stig/__init__.py", line 24, in run
    main.run()
  File "/usr/lib/python3.8/site-packages/stig/main.py", line 188, in run
    if not tui.run(run_commands):
  File "/usr/lib/python3.8/site-packages/stig/tui/main.py", line 207, in run
    urwidloop.run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.8/site-packages/stig/tui/urwidpatches.py", line 171, in run
    raise self._exc_info
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 1454, in faux_idle_callback
    callback()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 574, in entering_idle
    self.draw_screen()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 589, in draw_screen
    self.screen.draw_screen(self.screen_size, canvas)
  File "/usr/lib/python3.8/site-packages/urwid/raw_display.py", line 778, in draw_screen
    for row in r.content():
  File "/usr/lib/python3.8/site-packages/urwid/canvas.py", line 597, in content
    sbody = shard_body(cviews, shard_tail)
  File "/usr/lib/python3.8/site-packages/urwid/canvas.py", line 939, in shard_body
    raise CanvasError("cviews overflow gaps in"
urwid.canvas.CanvasError: cviews overflow gaps in shard_tail!
```

I restarted the client, re-did the exact same operation, and it worked.

**Comment by rndusr** [comment]
I've encountered similar crashes, but not for quite a while now. I suggest
installing stig from git/master until I make a new release. Should be less buggy
and you'd also help out in finding other bugs before the next release.

Please report if this happens again in current master or after the next release.

**Comment by lenormf** [comment]
I've installed the `master` version. Will re-open this issue if the bug occurs again.
