### ISSUE TITLE
[CRASH] Invalid modifier

### ISSUE THREAD

**Issue by lenormf** [rndusr/stig#136]
Hi,

I'm running the `master` version, and I triggered the following uncaught-exception upon hitting <kbd>shift</kbd><kbd>alt</kbd><kbd>→</kbd>:

```
Traceback (most recent call last):
  File "/usr/bin/stig", line 11, in <module>
    load_entry_point('stig==0.10.1a0', 'console_scripts', 'stig')()
  File "/usr/lib/python3.8/site-packages/stig/__init__.py", line 24, in run
    main.run()
  File "/usr/lib/python3.8/site-packages/stig/main.py", line 105, in run
    if not tui.run(run_commands):
  File "/usr/lib/python3.8/site-packages/stig/tui/main.py", line 63, in run
    tuiobjects.urwidloop.run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.8/site-packages/stig/tui/urwidpatches.py", line 175, in run    raise self._exc_info  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run    self._context.run(self._callback, *self._args)  File "/usr/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>    wrapper = lambda: self.parse_input(  File "/usr/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input    callback(processed, processed_codes)  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update    self.process_input(keys)  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input    k = self._topmost_widget.keypress(self.screen_size, k)  File "/usr/lib/python3.8/site-packages/stig/tui/keymap.py", line 168, in keypress    key_eval = Key(key_orig)  File "/usr/lib/python3.8/site-packages/stig/tui/keymap.py", line 70, in __new__
    raise ValueError('Invalid modifier in <%s>: <%s>' % (orig_key, mod))
ValueError: Invalid modifier in <shift meta right>: <meta>
```

**Comment by rndusr** [comment]
Doesn't happen for me. Which terminal are you using?

**Comment by lenormf** [comment]
I'm using Kitty.

**Comment by rndusr** [comment]
OK, I can reproduce it with kitty. Thanks.

**Comment by rndusr** [comment]
Should be fixed in master.

**Comment by lenormf** [comment]
Seems fixed, thanks!
