### ISSUE TITLE
Error in latest development version

### ISSUE THREAD

**Issue by BachoSeven** [rndusr/stig#140]
Hi, I experience this error running the latest stig version from today:

```
Traceback (most recent call last):
  File "/home/francesco/.local/bin/stig", line 8, in <module>
    sys.exit(run())
  File "/home/francesco/.local/pipx/venvs/stig/lib/python3.6/site-packages/stig/__init__.py", line 24, in run
    main.run()
  File "/home/francesco/.local/pipx/venvs/stig/lib/python3.6/site-packages/stig/main.py", line 38, in run
    'stig.commands.cli', 'stig.commands.tui',
  File "/home/francesco/.local/pipx/venvs/stig/lib/python3.6/site-packages/stig/commands/__init__.py", line 443, in load_cmds_from_module
    mod = import_module(modname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/francesco/.local/pipx/venvs/stig/lib/python3.6/site-packages/stig/commands/tui/__init__.py", line 18, in <module>
    from .tui import *
  File "/home/francesco/.local/pipx/venvs/stig/lib/python3.6/site-packages/stig/commands/tui/tui.py", line 1083, in <module>
    @functools.lru_cache
  File "/usr/lib/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

**Comment by rndusr** [comment]
Thanks for reporting. Should be fixed.
