### ISSUE TITLE
Crash when going past an exclamation mark on the prompt

### ISSUE THREAD

**Issue by lenormf** [rndusr/stig#141]
Hi,

Open up a prompt, type `ls !` then move the cursor past the exclamation point. The client crashes with the following stacktrace:

```
Traceback (most recent call last):
File "/usr/bin/stig", line 11, in <module>
load_entry_point('stig==0.10.1a0', 'console_scripts', 'stig')()
  File "/usr/lib/python3.8/site-packages/stig/__init__.py", line 24, in run
    main.run()
  File "/usr/lib/python3.8/site-packages/stig/main.py", line 105, in run
    if not tui.run(run_commands):
  File "/usr/lib/python3.8/site-packages/stig/tui/main.py", line 63, in run
    tuiobjects.urwidloop.run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.8/site-packages/stig/tui/urwidpatches.py", line 175, in run
    raise self._exc_info
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/site-packages/stig/tui/cli.py", line 197, in callback
    task.result()
  File "/usr/lib/python3.8/site-packages/stig/tui/completer.py", line 93, in update
    self._categories = await self._get_candidates_wrapper(args)
  File "/usr/lib/python3.8/site-packages/stig/tui/completer.py", line 40, in _get_candidates_wrapper
    cands = await maybe_await(self._get_candidates(args))
  File "/usr/lib/python3.8/site-packages/stig/tui/completer.py", line 37, in maybe_await
    x = await x
  File "/usr/lib/python3.8/site-packages/stig/completion/candidates.py", line 316, in torrent_filter
    return await _filter(curarg, 'TorrentFilter',
  File "/usr/lib/python3.8/site-packages/stig/completion/candidates.py", line 410, in _filter
    parts = filter_strings.curarg.separate(_utils.filter_compare_ops, include_seps=True)
AttributeError: 'NoneType' object has no attribute 'separate'
```

Reproduced on the master version, commit af31e6e.

**Comment by rndusr** [comment]
Fixed. Thanks for the report.
