### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by lenormf** [rndusr/stig#164]
Sorry no reproducers. I just added torrents randomly, and when I came back to the client *later* (minutes) it had crashed.

```
Traceback (most recent call last):
  File "/usr/bin/stig", line 11, in <module>
    load_entry_point('stig==0.11.0a0', 'console_scripts', 'stig')()
  File "/usr/lib/python3.8/site-packages/stig/__init__.py", line 25, in run
    main.run()
  File "/usr/lib/python3.8/site-packages/stig/main.py", line 102, in run
    if not tui.run(run_commands):
  File "/usr/lib/python3.8/site-packages/stig/tui/main.py", line 60, in run
    tuiobjects.urwidloop.run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.8/site-packages/stig/tui/urwidpatches.py", line 175, in run
    raise self._exc_info
  File "/usr/lib/python3.8/site-packages/stig/client/base.py", line 235, in _gather_info_wrapper_coro
    free = await self._get_free_space(path)
  File "/usr/lib/python3.8/site-packages/stig/client/aiotransmission/api_freespace.py", line 21, in _get_free_space
    response = await self._space_getter(path=path)
  File "/usr/lib/python3.8/site-packages/stig/client/aiotransmission/rpc.py", line 458, in request
    rpc_request = json.dumps({'method'    : method.replace('_', '-'),
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Constant is not JSON serializable
```

**Comment by rndusr** [comment]
Thanks! I was going to release just about when you made the report.

I think I'm going to wait a bit longer.
