### ISSUE TITLE
Error when starting first time

### ISSUE THREAD

**Issue by ManuCart** [rndusr/stig#20]
Hi,

I have this error when I'm starting first ime
````
Traceback (most recent call last):
  File "/usr/local/bin/stig", line 11, in <module>
    load_entry_point('stig==0.4.0a0', 'console_scripts', 'stig')()
  File "/usr/local/lib/python3.4/dist-packages/stig/__init__.py", line 16, in run
    from . import main
  File "/usr/local/lib/python3.4/dist-packages/stig/main.py", line 19, in <module>
    cliargs, clicmds = cliopts.parse()
  File "/usr/local/lib/python3.4/dist-packages/stig/cliopts.py", line 89, in parse
    from .commands import is_op
  File "/usr/local/lib/python3.4/dist-packages/stig/commands/__init__.py", line 287
    async def wait_async(self):
            ^
SyntaxError: invalid syntax
````

**Comment by rndusr** [comment]
Looks like you're using Python 3.4. The minimum is 3.5.

**Comment by ManuCart** [comment]
OK thanks, working with Python 3.6
