### ISSUE TITLE
crash when marking files

### ISSUE THREAD

**Issue by karasuma-chitose** [rndusr/stig#21]
When I use space to mark files, stig immediately crashes with the following error message
```
Traceback (most recent call last):
  File "/usr/bin/stig", line 11, in <module>
    load_entry_point('stig==0.4.0a0', 'console_scripts', 'stig')()
  File "/usr/lib/python3.6/site-packages/stig/__init__.py", line 17, in run
    main.run()
  File "/usr/lib/python3.6/site-packages/stig/main.py", line 119, in run
    if not tui.run(run_commands):
  File "/usr/lib/python3.6/site-packages/stig/tui/main.py", line 148, in run
    urwidloop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.6/site-packages/stig/tui/urwidpatches.py", line 45, in run
    raise self._exc_info
  File "/usr/lib/python3.6/site-packages/stig/commands/__init__.py", line 563, in run_async
    self._maybe_run_callbacks(process, on_success, on_error)
  File "/usr/lib/python3.6/site-packages/stig/commands/__init__.py", line 509, in _maybe_run_callbacks
    raise exc
  File "/usr/lib/python3.6/site-packages/stig/commands/__init__.py", line 240, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/stig/commands/tui/tui.py", line 175, in run
    widget.mark(toggle=toggle, all=all)
  File "/usr/lib/python3.6/site-packages/stig/tui/torrent/flist.py", line 322, in mark
    self._set_mark(True, toggle=toggle, all=all)
  File "/usr/lib/python3.6/site-packages/stig/tui/torrent/flist.py", line 363, in _set_mark
    mark_leaves(self._listbox.focus_position, mark)
  File "/usr/lib/python3.6/site-packages/stig/tui/torrent/flist.py", line 343, in mark_leaves
    get_widget(pos).is_marked = mark
  File "/usr/lib/python3.6/site-packages/stig/tui/torrent/flist.py", line 340, in get_widget
    return self._listbox.contents[pos][0].original_widget
TypeError: 'method' object is not subscriptable
```
I'm using Arch Linux.

**Comment by karasuma-chitose** [comment]
The same thing happens on FreeBSD 11.
```
Traceback (most recent call last):
  File "/usr/local/bin/stig", line 11, in <module>
    load_entry_point('stig==0.4.0a0', 'console_scripts', 'stig')()
  File "/usr/local/lib/python3.6/site-packages/stig-0.4.0a0-py3.6.egg/stig/__init__.py", line 17, in run
    main.run()
  File "/usr/local/lib/python3.6/site-packages/stig-0.4.0a0-py3.6.egg/stig/main.py", line 119, in run
    if not tui.run(run_commands):
  File "/usr/local/lib/python3.6/site-packages/stig-0.4.0a0-py3.6.egg/stig/tui/main.py", line 148, in run
    urwidloop.run()
  File "/usr/local/lib/python3.6/site-packages/urwid-1.3.1-py3.6-freebsd-11.0-RELEASE-p2-amd64.egg/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python3.6/site-packages/urwid-1.3.1-py3.6-freebsd-11.0-RELEASE-p2-amd64.egg/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.6/site-packages/stig-0.4.0a0-py3.6.egg/stig/tui/urwidpatches.py", line 45, in run
    raise self._exc_info
  File "/usr/local/lib/python3.6/site-packages/stig-0.4.0a0-py3.6.egg/stig/commands/__init__.py", line 563, in run_async
    self._maybe_run_callbacks(process, on_success, on_error)
  File "/usr/local/lib/python3.6/site-packages/stig-0.4.0a0-py3.6.egg/stig/commands/__init__.py", line 509, in _maybe_run_callbacks
    raise exc
  File "/usr/local/lib/python3.6/site-packages/stig-0.4.0a0-py3.6.egg/stig/commands/__init__.py", line 240, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/stig-0.4.0a0-py3.6.egg/stig/commands/tui/tui.py", line 175, in run
    widget.mark(toggle=toggle, all=all)
  File "/usr/local/lib/python3.6/site-packages/stig-0.4.0a0-py3.6.egg/stig/tui/torrent/flist.py", line 322, in mark
    self._set_mark(True, toggle=toggle, all=all)
  File "/usr/local/lib/python3.6/site-packages/stig-0.4.0a0-py3.6.egg/stig/tui/torrent/flist.py", line 363, in _set_mark
    mark_leaves(self._listbox.focus_position, mark)
  File "/usr/local/lib/python3.6/site-packages/stig-0.4.0a0-py3.6.egg/stig/tui/torrent/flist.py", line 343, in mark_leaves
    get_widget(pos).is_marked = mark
  File "/usr/local/lib/python3.6/site-packages/stig-0.4.0a0-py3.6.egg/stig/tui/torrent/flist.py", line 340, in get_widget
    return self._listbox.contents[pos][0].original_widget
TypeError: 'method' object is not subscriptable
```

**Comment by rndusr** [comment]
Looks like this is an urwid issue with python 3.6.
3.5 works fine.
