### ISSUE TITLE
aiohttp update breakage

### ISSUE THREAD

**Issue by karasuma-chitose** [rndusr/stig#26]
stig stopped working on Arch after an update a couple of days ago.
Here's the output:
```
$ stig
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/stig/tui/main.py", line 153, in run
    urwidloop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.6/site-packages/stig/tui/urwidpatches.py", line 45, in run
    raise self._exc_info
  File "/usr/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/site-packages/stig/client/poll.py", line 73, in reraise
    task.result()
  File "/usr/lib/python3.6/site-packages/stig/client/poll.py", line 85, in _poll_loop
    await self._poll_task
  File "/usr/lib/python3.6/site-packages/stig/client/poll.py", line 114, in _do_poll
    response = await self._request()
  File "/usr/lib/python3.6/site-packages/stig/client/aiotransmission/api_torrent.py", line 297, in torrents
    return await self._get_torrents_by_ids(keys, autoconnect=autoconnect)
  File "/usr/lib/python3.6/site-packages/stig/client/aiotransmission/api_torrent.py", line 211, in _get_torrents_by_ids
    response = await self._request_torrents(fields, ids)
  File "/usr/lib/python3.6/site-packages/stig/client/aiotransmission/api_torrent.py", line 168, in _request_torrents
    raw_tlist = await self.rpc.torrent_get(fields=fields)
  File "/usr/lib/python3.6/site-packages/stig/client/aiotransmission/rpc.py", line 393, in request
    return await self.__send_request(rpc_request)
  File "/usr/lib/python3.6/site-packages/stig/client/aiotransmission/rpc.py", line 347, in __send_request
    answer = await self.__post(post_data)
  File "/usr/lib/python3.6/site-packages/stig/client/aiotransmission/rpc.py", line 307, in __post
    response = await self.__session.post(repr(self.__url), data=data, headers=self.__headers)
  File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 631, in __await__
    resp = yield from self._coro
  File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 230, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 385, in connect
    self._acquired.remove(placeholder)
KeyError: <aiohttp.connector._TransportPlaceholder object at 0x7f77d39fb390>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/stig", line 11, in <module>
    load_entry_point('stig==0.4.1a0', 'console_scripts', 'stig')()
  File "/usr/lib/python3.6/site-packages/stig/__init__.py", line 17, in run
    main.run()
  File "/usr/lib/python3.6/site-packages/stig/main.py", line 119, in run
    if not tui.run(run_commands):
  File "/usr/lib/python3.6/site-packages/stig/tui/main.py", line 156, in run
    aioloop.run_until_complete(srvapi.stop_polling())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 464, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```
python related stuff from my pacman.log:
```
[2017-06-02 22:51] [ALPM] upgraded python-setuptools (1:35.0.2-1 -> 1:36.0.1-1)
[2017-06-02 22:51] [ALPM] upgraded python-chardet (3.0.2-1 -> 3.0.3-1)
[2017-06-02 22:51] [ALPM] upgraded python-multidict (2.1.4-1 -> 2.1.6-1)
[2017-06-02 22:51] [ALPM] upgraded python-async-timeout (1.2.0-2 -> 1.2.1-2)
[2017-06-02 22:51] [ALPM] upgraded python-yarl (0.9.8-1 -> 0.10.2-2)
[2017-06-02 22:51] [ALPM] upgraded python-aiohttp (1.3.1-1 -> 2.1.0-1)
```
Nothing else relevant was upgraded as far as I can tell.
python-aiohttp is the only stig dependency here and it was mentioned in the error output, so I guess that's the problem.

**Comment by rndusr** [comment]
Fixed in current dev branch. Please use that (`stig-git` package in Arch) until the new release is out (should be soon).
