### ISSUE TITLE
TimeoutError crash on connection loss

### ISSUE THREAD

**Issue by sometoby** [rndusr/stig#33]
### Steps To Reproduce

1. Run stig and let it connect to a server
2. Interrupt the connection by some means (I simply turned off WiFi)
3. Wait for stig to crash due to an unhandled TimeoutError

```
Traceback (most recent call last):
  File "/Users/tobias/.virtualenvs/stig/bin/stig", line 11, in <module>
    load_entry_point('stig==0.7.3a0', 'console_scripts', 'stig')()
  File "/Users/tobias/.virtualenvs/stig/lib/python3.6/site-packages/stig-0.7.3a0-py3.6.egg/stig/__init__.py", line 17, in run
    main.run()
  File "/Users/tobias/.virtualenvs/stig/lib/python3.6/site-packages/stig-0.7.3a0-py3.6.egg/stig/main.py", line 119, in run
    if not tui.run(run_commands):
  File "/Users/tobias/.virtualenvs/stig/lib/python3.6/site-packages/stig-0.7.3a0-py3.6.egg/stig/tui/main.py", line 212, in run
    urwidloop.run()
  File "/Users/tobias/.virtualenvs/stig/lib/python3.6/site-packages/urwid-1.3.1-py3.6-macosx-10.12-x86_64.egg/urwid/main_loop.py", line 278, in run
    self._run()
  File "/Users/tobias/.virtualenvs/stig/lib/python3.6/site-packages/urwid-1.3.1-py3.6-macosx-10.12-x86_64.egg/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/Users/tobias/.virtualenvs/stig/lib/python3.6/site-packages/stig-0.7.3a0-py3.6.egg/stig/tui/urwidpatches.py", line 56, in run
    raise self._exc_info
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out
```

The crash can be prevented by changing line 40 of `stig/tui/urwidpatches.py` to:
```python
        if exc and not isinstance(exc, TimeoutError):
```
This prevents the crash, and stig connects to the server just fine when the connection is restored. This isn't exactly a fix of course, but I'm not sure how or where the exception ought to be dealt with.

**Comment by rndusr** [comment]
Yeah, that's not the correct fix. The fix should probably be in client.aiotransmission.rpc.

Everything works as expected if I simply shutdown the daemon, so turning of wifi must raise a different exception at some point.

It's hard for me to reproduce this because I don't have wifi. Any chance you might be interested in debugging this?

**Comment by hhiru** [comment]
Looks like he's ok with that quickfix but I'd like to help you debugging this further. I'm using a laptop so I can hopefully help you posting here the results

**Comment by rndusr** [comment]
That would be great, thanks.

Pull the latest dev branch and run this to turn on debugging messages for the
rpc module:

stig --debug client.aiotransmission.rpc --debug-file timeout.log

**Comment by sometoby** [comment]
@hhiru I'm definitely not ok with the quickfix, but I've been otherwise occupied. Thank you for giving debugging this a shot! 😊

**Comment by rndusr** [comment]
I think I've found a way to simulate turning off wifi (`ip addr del
127.0.0.1/8 dev lo`) and everything is working as expected: stig loses the
connection and re-connects when the device comes back up (`ip addr add
127.0.0.1/8 dev lo`).

@sometoby, can you confirm that the issue persists for you with the latest dev
branch?

**Comment by hhiru** [comment]
> Pull the latest dev branch
I installed stig via AUR, should I install stig-git? Is that the dev branch?

**Comment by rndusr** [comment]
Yes, stig-git should install the dev branch.

**Comment by hhiru** [comment]
I installed and run the dev branch, tested disabling wifi via the manual swtich getting the error connetion (not a crash) and I re-enabled the wifi causing stig to reconnect to the web server. Everything seems to work fine

**Comment by rndusr** [comment]
I assume this is fixed.
