### ISSUE TITLE
Handle the KeyboardInterrupt exception

### ISSUE THREAD

**Issue by ryukinix** [rndusr/stig#39]
Steps: open stig and press `C-c`.
```
~
❯ stig
Traceback (most recent call last):
  File "/usr/bin/stig", line 11, in <module>
    load_entry_point('stig==0.7.3a0', 'console_scripts', 'stig')()
  File "/usr/lib/python3.6/site-packages/stig/__init__.py", line 17, in run
    main.run()
  File "/usr/lib/python3.6/site-packages/stig/main.py", line 119, in run
    if not tui.run(run_commands):
  File "/usr/lib/python3.6/site-packages/stig/tui/main.py", line 212, in run
    urwidloop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.6/site-packages/stig/tui/urwidpatches.py", line 54, in run
    self._loop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1390, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
```
Would be nice if as most all other programs, we can exit with `C-c` (SIGINT interrupt signal). 
Since are you using a `asyncio` loop, you could just attach the sigint to finish the program as I did [here](https://github.com/ryukinix/decorating/blob/master/decorating/animation.py#L343) using the `signal` module of stdlib.

**Comment by rndusr** [comment]
In the latest release, you can now bind ctrl-c like any other key.

**Comment by ryukinix** [comment]
@mdusr thanks for implementing that :)

**Comment by rndusr** [comment]
Sure thing!
Thanks for reporting the bug. (:
