### ISSUE TITLE
AttributeError: 'TransmissionURL' object has no attribute 'username'

### ISSUE THREAD

**Issue by sometoby** [rndusr/stig#43]
When trying to run stig 0.8.0a with the following config:

```
set srv.url https://rpc:hunter2@seedbox.example.com/transmission/rpc/
```

… stig fails to start and prints these tracebacks:

```
Task exception was never retrieved
future: <Task finished coro=<_connect_to_new_url.<locals>.coro() done, defined at /usr/local/lib/python3.6/site-packages/stig/tui/hooks.py:30> exception=AttributeError("'TransmissionURL' object has no attribute 'username'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/stig/tui/hooks.py", line 32, in coro
    await srvapi.rpc.connect(url.value)
  File "/usr/local/lib/python3.6/site-packages/stig/client/aiotransmission/rpc.py", line 202, in connect
    session_args['auth'] = aiohttp.BasicAuth(self.__url.username,
AttributeError: 'TransmissionURL' object has no attribute 'username'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/stig/tui/main.py", line 186, in run
    urwidloop.run()
  File "/usr/local/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.6/site-packages/stig/tui/urwidpatches.py", line 93, in run
    raise self._exc_info
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/stig/client/poll.py", line 77, in reraise
    task.result()
  File "/usr/local/lib/python3.6/site-packages/stig/client/poll.py", line 87, in _poll_loop
    await self._poll_task
  File "/usr/local/lib/python3.6/site-packages/stig/client/poll.py", line 116, in _do_poll
    response = await self._request()
  File "/usr/local/lib/python3.6/site-packages/stig/client/aiotransmission/api_torrent.py", line 365, in torrents
    return await self._get_torrents_by_ids(keys)
  File "/usr/local/lib/python3.6/site-packages/stig/client/aiotransmission/api_torrent.py", line 274, in _get_torrents_by_ids
    response = await self._request_torrents(fields, ids)
  File "/usr/local/lib/python3.6/site-packages/stig/client/aiotransmission/api_torrent.py", line 233, in _request_torrents
    raw_tlist = await self.rpc.torrent_get(fields=fields)
  File "/usr/local/lib/python3.6/site-packages/stig/client/aiotransmission/rpc.py", line 344, in request
    await self.connect()
  File "/usr/local/lib/python3.6/site-packages/stig/client/aiotransmission/rpc.py", line 202, in connect
    session_args['auth'] = aiohttp.BasicAuth(self.__url.username,
AttributeError: 'TransmissionURL' object has no attribute 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/stig", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/stig/__init__.py", line 22, in run
    main.run()
  File "/usr/local/lib/python3.6/site-packages/stig/main.py", line 155, in run
    if not tui.run(run_commands):
  File "/usr/local/lib/python3.6/site-packages/stig/tui/main.py", line 189, in run
    aioloop.run_until_complete(srvapi.stop_polling())
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/stig/client/api.py", line 218, in stop_polling
    await poller.stop()
  File "/usr/local/lib/python3.6/site-packages/stig/client/aiotransmission/api_status.py", line 36, in stop
    await self._poller_stats.stop(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/stig/client/poll.py", line 157, in stop
    await asyncio.wait_for(self._poll_loop_task, timeout=0, loop=self.loop)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/stig/client/poll.py", line 77, in reraise
    task.result()
  File "/usr/local/lib/python3.6/site-packages/stig/client/poll.py", line 87, in _poll_loop
    await self._poll_task
  File "/usr/local/lib/python3.6/site-packages/stig/client/poll.py", line 116, in _do_poll
    response = await self._request()
  File "/usr/local/lib/python3.6/site-packages/stig/client/aiotransmission/rpc.py", line 344, in request
    await self.connect()
  File "/usr/local/lib/python3.6/site-packages/stig/client/aiotransmission/rpc.py", line 202, in connect
    session_args['auth'] = aiohttp.BasicAuth(self.__url.username,
AttributeError: 'TransmissionURL' object has no attribute 'username'
```

**Comment by rndusr** [comment]
Sorry about that. I made another bugfix release that fixes this.

**Comment by sometoby** [comment]
That did the trick. Thanks for the quick fix!
