### ISSUE TITLE
Failure to run 'stig info id=<id>': KeyError: 'name'

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#57]
I have just installed stig from source, was playing around to learn how to use it and stumbled across a problem: I wanted to show info about a torrent using its torrent id as filter, so I tried:

```
stig info id=43
```

and this is the result:

```
paulo@monk:~/src/stig$ stig summary id=43
Traceback (most recent call last):
  File "/home/paulo/.local/bin/stig", line 11, in <module>
    load_entry_point('stig==0.8.3a0', 'console_scripts', 'stig')()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/__init__.py", line 24, in run
    main.run()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/main.py", line 169, in run
    if not run_commands():
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/main.py", line 151, in run_commands
    success = cmdmgr.run_sync(clicmds, on_error=log.error)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 576, in run_sync
    self._maybe_run_callbacks(process, on_success, on_error)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 529, in _maybe_run_callbacks
    raise exc
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 243, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 243, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/base/torrent.py", line 106, in run
    return await self.display_summary(tfilter)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/cli/torrent.py", line 55, in display_summary
    torrent = await self.get_torrent(tfilter, keys=('id',))
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/base/_mixin.py", line 40, in get_torrent
    torrents = TorrentSorter(('name',)).apply(response.torrents)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/client/sorters/__init__.py", line 106, in apply
    items = sorter(items, inplace=inplace, item_getter=item_getter)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/client/sorters/__init__.py", line 35, in __call__
    items = sorted(items, key=key_getter, reverse=reverse)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/client/sorters/__init__.py", line 30, in key_getter
    return keyfunc(item_getter(item))
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/client/sorters/torrent.py", line 26, in <lambda>
    'name':              _SortSpec(lambda t: t['name'].lower(),
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/client/aiotransmission/torrent.py", line 496, in __getitem__
    value = raw[fields[0]]
KeyError: 'name'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb41a4e5940>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fb41e03a668>, 159348.330755063)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fb41a4e5748>
```

I'm running Xubuntu 17.10 and this is how I installed stig

```
git clone https://github.com/rndusr/stig
cd stig
python3 setup.py install --user
```

The torrent id I was trying to filter against exists, here's the output from _transmission-remote_:

```
ID     Done       Have  ETA           Up    Down  Ratio  Status       Name
  43   100%    7.53 GB  Done         0.0     0.0    0.5  Idle         Sneaky Pete
  47   100%   271.5 MB  Unknown      0.0     0.0    6.3  Idle         Good.Girls.S01E03.HDTV.x264-SVA[eztv].mkv
Sum:           7.81 GB               0.0     0.0
```

**Comment by marcelpaulo** [comment]
I've just discovered that I can filter by torrent id with another command:

`stig ls id=43`

It looks as though it's only `info` that generates the error I reported.

**Comment by rndusr** [comment]
Thansk for the extensive info. Should be fixed in current master.

**Comment by marcelpaulo** [comment]
I've just pulled and tested it, and indeed it's fixed ! Thanks for the speed-lightning fix, @rndusr !

This is a fabulous transmission client, extremely useful, flexible and extensive ! Congratulations !

**Comment by rndusr** [comment]
Thank you. I'm glad you like it. :)
