### ISSUE TITLE
"stig set" not listing all settings: 'SetCmd' object has no attribute 'make_setting_list'

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#63]
Yesterday I thought of asking if there was a way of dumping all current settings, and then by chance I saw that you implemented it today with ff5b629609e7415d5ad48386b19c0e54fba9d59c. So I updated to master, installed, and here's what happens when I ran `stig set`:

```
paulo@monk:~/src/stig$ stig set
Traceback (most recent call last):
  File "/home/paulo/.local/bin/stig", line 11, in <module>
    load_entry_point('stig==0.8.3a0', 'console_scripts', 'stig')()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/__init__.py", line 24, in run
    main.run()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/main.py", line 170, in run
    if not run_commands():
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/main.py", line 152, in run_commands
    success = cmdmgr.run_sync(clicmds, on_error=log.error)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 576, in run_sync
    self._maybe_run_callbacks(process, on_success, on_error)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 529, in _maybe_run_callbacks
    raise exc
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 243, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 243, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/base/config.py", line 128, in run
    self.make_setting_list(sort)
AttributeError: 'SetCmd' object has no attribute 'make_setting_list'
```

**Comment by rndusr** [comment]
Yup, the CLI version is not implemented yet. It should work in the TUI:

    stig tab set

**Comment by marcelpaulo** [comment]
Yeah, it does ! This is really useful ! Thanks !

**Comment by rndusr** [comment]
BTW, you can also edit the values by pressing enter. But it's not done yet; you
still have to manually edit the text. For example, boolean values should just
toggle.
