### ISSUE TITLE
Print setting list in CLI mode breaks when a setting is blank: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#66]
Great that you implemented `stig set` to print the settings in CLI mode ! However, it's throwing the error `IndexError: tuple index out of range` when it meets a setting with a blank value:

```
paulo@monk:~/src/stig$ stig set
Name                   │Value                                                                               │Description                                                                          
columns.files          │marked, priority, progress, downloaded, size, name                                  │Default columns in file lists                                                        
columns.peers          │client, country, ip, progress, rate-down, rate-up, rate-est, eta                    │Default columns in peer lists                                                        
columns.settings       │name, value, description                                                            │Default columns in setting lists                                                     
columns.torrents       │marked, size, downloaded, uploaded, ratio, seeds, connections, status, progress,    │Default columns in torrent lists                                                     
                       │eta, time-activity, rate-down, rate-up, name                                        │                                                                                     
columns.trackers       │tier, domain, state, error, leeches, seeds, downloads, last-announce, next-announce │Default columns in tracker lists                                                     
connect.host           │localhost                                                                           │Hostname or IP of Transmission RPC interface                                         
Traceback (most recent call last):
  File "/home/paulo/.local/bin/stig", line 11, in <module>
    load_entry_point('stig==0.8.3a0', 'console_scripts', 'stig')()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/__init__.py", line 24, in run
    main.run()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/main.py", line 170, in run
    if not run_commands():
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/main.py", line 152, in run_commands
    success = cmdmgr.run_sync(clicmds, on_error=log.error)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 576, in run_sync
    self._maybe_run_callbacks(process, on_success, on_error)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 529, in _maybe_run_callbacks
    raise exc
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 243, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 243, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/base/config.py", line 146, in run
    self.make_setting_list(sort, columns)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/cli/config.py", line 44, in make_setting_list
    print_table(settings, columns, SETTING_COLUMNS)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/cli/_table.py", line 252, in print_table
    for row in _assemble_row(table, line_index, pretty=pretty_output):
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/cli/_table.py", line 67, in _assemble_row
    empty_space = ' ' * len(cell[0])
IndexError: tuple index out of range
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f079a885f60>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f079fdd36a0>, 77977.556054132)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f079bcf06d8>
```

For reference, here's a screenshot of the values in the TUI:

![image](https://user-images.githubusercontent.com/10074769/37618274-8a67b1ee-2b94-11e8-9c95-0779c18ae8a9.png)

I get the impression it breaks when the setting has no value, like `connect.password`. I set `connect.password` to _foo_, and it broke on `connect.user`, which is currently blank:

```
paulo@monk:~/src/stig$ stig set
Name                   │Value                                                                               │Description                                                                          
columns.files          │marked, priority, progress, downloaded, size, name                                  │Default columns in file lists                                                        
columns.peers          │client, country, ip, progress, rate-down, rate-up, rate-est, eta                    │Default columns in peer lists                                                        
columns.settings       │name, value, description                                                            │Default columns in setting lists                                                     
columns.torrents       │marked, size, downloaded, uploaded, ratio, seeds, connections, status, progress,    │Default columns in torrent lists                                                     
                       │eta, time-activity, rate-down, rate-up, name                                        │                                                                                     
columns.trackers       │tier, domain, state, error, leeches, seeds, downloads, last-announce, next-announce │Default columns in tracker lists                                                     
connect.host           │localhost                                                                           │Hostname or IP of Transmission RPC interface                                         
connect.password       │foo                                                                                 │Password to use for authentication with Transmission RPC interface                   
connect.path           │/transmission/rpc                                                                   │Path of Transmission RPC interface                                                   
connect.port           │9091                                                                                │Port of Transmission RPC interface                                                   
connect.timeout        │10                                                                                  │Number of seconds before connecting to Transmission RPC interface fails              
connect.tls            │off                                                                                 │Whether to connect via HTTPS to the Transmission RPC interface                       
Traceback (most recent call last):
  File "/home/paulo/.local/bin/stig", line 11, in <module>
    load_entry_point('stig==0.8.3a0', 'console_scripts', 'stig')()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/__init__.py", line 24, in run
    main.run()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/main.py", line 170, in run
    if not run_commands():
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/main.py", line 152, in run_commands
    success = cmdmgr.run_sync(clicmds, on_error=log.error)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 576, in run_sync
    self._maybe_run_callbacks(process, on_success, on_error)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 529, in _maybe_run_callbacks
    raise exc
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 243, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 243, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/base/config.py", line 146, in run
    self.make_setting_list(sort, columns)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/cli/config.py", line 44, in make_setting_list
    print_table(settings, columns, SETTING_COLUMNS)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/cli/_table.py", line 252, in print_table
    for row in _assemble_row(table, line_index, pretty=pretty_output):
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/cli/_table.py", line 67, in _assemble_row
    empty_space = ' ' * len(cell[0])
IndexError: tuple index out of range
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fdadc8a4fd0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fdae1df16a0>, 78502.611046043)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fdaddd0e4a8>
```

**Comment by rndusr** [comment]
Thanks. Should be fixed now.

And thank you in general for running the development version. It's a relief to
have some bug-reporting beta testers.

**Comment by marcelpaulo** [comment]
Confirmed: fixed ! Thanks !

You can count on me ! I use stig all the time, I really like it, I'll try to keep abreast of master and will be testing your new implementations.

**Comment by rndusr** [comment]
And you can count on my to provide you with plenty of bugs to report. :)
