### ISSUE TITLE
Is it possible to set individual files of a torrent for not downloading ?

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#68]
I've just opened up a tab with the filelist from a torrent, I can mark individual files, but I can't find a command to set these files for not downloading. I looked at each one of the help files, perhaps I overlooked something. It would be something like the option `--no-get` of _transmission-remote_.

**Comment by rndusr** [comment]
`stig priority off <torrents> <files>`

In the TUI, it's bound to 0 (off), - (low), = (normal), + (high).

**Comment by marcelpaulo** [comment]
I can't seem to get it to work, perhaps I'm doing something wrong. 

In the TUI:

1. I started downloading a torrent for testing, opened a tab with its filelist
![screenshot_2018-03-22_15-38-01](https://user-images.githubusercontent.com/10074769/37791188-526bac0a-2de7-11e8-9117-4196beb7add6.png)

2. Selected some files to stop downloading
3. Pressed `0`. As I can see in the log, the priority of all files of **other** torrents was set to off, but the files I selected were not touched:
![screenshot_2018-03-22_15-38-44](https://user-images.githubusercontent.com/10074769/37791206-5f7fda74-2de7-11e8-8295-c08b575c2a52.png)

Trying in the CLI:

1. Making sure I could select the torrent by name:

```
paulo@monk:~/src/stig$ stig ls beatles
Size B│Dn B│Up B│Ratio│Seeds│Conn│Status│   %│ETA│Activity│Dn b/s│Up b/s│Name                                
 86.6M│ 68k│   0│    0│    ?│   0│  idle│0.07│   │   15:37│     0│     0│1990 - Aki Takahashi - Hyper Beatles
```

2. Showed its filelist:

```
paulo@monk:~/src/stig$ stig lsf beatles
Priority│   %│Dn  B│Size B│Filename                                                     
        │0.08│65.5k│ 86.6M│1990 - Aki Takahashi - Hyper Beatles                         
        │   0│    0│ 4.32M│  01 - Here, There and Everywhere.mp3                        
        │   0│    0│ 3.28M│  02 - Blackbird.mp3                                         
        │   0│    0│ 2.73M│  03 - Hide & Seek in Norwegian Wood.mp3                     
        │   0│    0│ 3.77M│  04 - Here Comes Lucy-Here Comes the Sun.mp3                
        │   0│    0│ 6.81M│  05 - Yesterday.mp3                                         
        │   0│    0│ 5.42M│  06 - When Im 64.mp3                                        
        │   0│    0│ 8.14M│  07 - Something.mp3                                         
        │   0│    0│ 11.8M│  08 - The Beatles 1962-1970.mp3                             
        │   0│    0│ 5.62M│  09 - Michelle.mp3                                          
        │   0│    0│ 7.48M│  10 - And I love Her.mp3                                    
        │   0│    0│ 4.57M│  11 - She Said, She Said.mp3                                
        │   0│    0│ 5.43M│  12 - The Fool on the Hill-1.mp3                            
        │   0│    0│ 5.46M│  13 - The Fool on The Hill-2.mp3                            
        │   0│    0│ 4.81M│  14 - Goddess of Liberty-You got to Hide  Your Love Away.mp3
        │0.96│65.5k│ 6.84M│  15 - Short Fantasy on-Give Peace a Chance.mp3              
        │   0│    0│   920│  Album info.txt                                             
        │   0│    0│  172k│  Cover                                                      
        │   0│    0│ 64.2k│    1.jpg                                                    
        │   0│    0│  108k│    2.jpg                                                    
```

3. Tried to set the priority to off for the same files I had selected in the TUI:

```
paulo@monk:~/src/stig$ stig prio off beatles '03|04|05|06'
Traceback (most recent call last):
  File "/home/paulo/.local/bin/stig", line 11, in <module>
    load_entry_point('stig==0.8.3a0', 'console_scripts', 'stig')()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/__init__.py", line 24, in run
    main.run()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/main.py", line 161, in run
    if not run_commands():
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/main.py", line 147, in run_commands
    success = cmdmgr.run_sync(clicmds, on_error=log.error)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 576, in run_sync
    self._maybe_run_callbacks(process, on_success, on_error)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 529, in _maybe_run_callbacks
    raise exc
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 243, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/__init__.py", line 243, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/base/file.py", line 116, in run
    discover_file=True)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/commands/cli/_mixin.py", line 131, in select_files
    return TorrentFileFilter(FILTER)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/client/filters/__init__.py", line 294, in __init__
    f = self.filterclass(part)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.8.3a0-py3.6.egg/stig/client/filters/__init__.py", line 203, in __init__
    tuple(self.COMPARATIVE_FILTERS))))
RuntimeError: Default filter 'name' does not exist: 'all, wanted, complete, file, path, size, downloaded, %downloaded, priority'
```

**Comment by rndusr** [comment]
Confirmed. I'll try to fix that tomorrow.

**Comment by rndusr** [comment]
I think I fixed it. (Sorry about the delay.)

**Comment by marcelpaulo** [comment]
Hey, @rndusr, no need to apologize: you're generously giving you time in developing stig, so I'm thankful for that, whenever you have the time.

It's working flawlessly, both with the CLI and the TUI !

One minor observation, perhaps it was the intended behaviour, in the TUI, when I select files and change their priority, the files stay selected after the priority is changed: shouldn't they be unselected after the operation is completed ?

**Comment by rndusr** [comment]
Thanks for understanding and testing.

Selections are currently not removed when they are used for something. I agree,
it's kind of annoying, but it's also really easy to remove them by pressing
<alt-space> once or twice.

But I'll make this configurable at some point.

**Comment by marcelpaulo** [comment]
> Selections are currently not removed when they are used for something

Oh, you're right. Until now, I only used selections to remove torrents, so hadn't realized they do persist after the operation is completed (have just tested with stopping selected torrents). It kind of makes sense to leave them selected, in case one wants to do other stuff with them. And, as you said, it's no trouble unselecting them.
