### ISSUE TITLE
After a fresh installation in a virtualenv I get an error

### ISSUE THREAD

**Issue by doronbehar** [rndusr/stig#72]
Here is the traceback:
```
Traceback (most recent call last):
  File "/home/doron/.local/bin/stig", line 11, in <module>
    load_entry_point('stig==0.8.3a0', 'console_scripts', 'stig')()
  File "/home/doron/.virtualenv/stig/lib/python3.6/site-packages/stig/__init__.py", line 18, in run
    from . import main
  File "/home/doron/.virtualenv/stig/lib/python3.6/site-packages/stig/main.py", line 65, in <module>
    os.path.basename(geoip.filepath))
  File "/usr/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by rndusr** [comment]
Thanks for the report. I almost made a new release today.

**Comment by rndusr** [comment]
Should be fixed now.
