### ISSUE TITLE
Crash when showing peerlist on TUI: KeyError: 'country'

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#76]
Running the TUI, I tried to show the peer list for a torrent (`t p` over the torrent), and stig crashed to the shell, throwing this exception:

```
Traceback (most recent call last):
  File "/home/paulo/.local/bin/stig", line 11, in <module>
    load_entry_point('stig==0.9.0a0', 'console_scripts', 'stig')()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/__init__.py", line 24, in run
    main.run()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/main.py", line 186, in run
    if not tui.run(run_commands):
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/main.py", line 190, in run
    urwidloop.run()
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid-2.0.1-py3.6-linux-x86_64.egg/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid-2.0.1-py3.6-linux-x86_64.egg/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/urwidpatches.py", line 144, in run
    raise self._exc_info
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid-2.0.1-py3.6-linux-x86_64.egg/urwid/main_loop.py", line 1443, in faux_idle_callback
    callback()
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid-2.0.1-py3.6-linux-x86_64.egg/urwid/main_loop.py", line 572, in entering_idle
    self.draw_screen()
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid-2.0.1-py3.6-linux-x86_64.egg/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid-2.0.1-py3.6-linux-x86_64.egg/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid-2.0.1-py3.6-linux-x86_64.egg/urwid/widget.py", line 1765, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid-2.0.1-py3.6-linux-x86_64.egg/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid-2.0.1-py3.6-linux-x86_64.egg/urwid/container.py", line 1529, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid-2.0.1-py3.6-linux-x86_64.egg/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/tabs.py", line 129, in render
    canvas = current_widget.render(size_content, focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid-2.0.1-py3.6-linux-x86_64.egg/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/views/__init__.py", line 227, in render
    self._update_listitems()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/views/__init__.py", line 267, in _update_listitems
    walker.append(cls(data_dict[data_id], item_widget))
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/views/__init__.py", line 133, in __init__
    self.update(data)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/views/__init__.py", line 138, in update
    widget.update(data)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/views/__init__.py", line 90, in update
    new_value = self.get_value()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/views/peer.py", line 61, in get_value
    return self.data['country']
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/client/ttypes.py", line 564, in __getitem__
    val = self._MODIFIERS[key](self._dct)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/client/ttypes.py", line 546, in <lambda>
    'country' : lambda p: geoip.country_code(p['ip']) or '?',
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/client/geoip.py", line 150, in country_code
    country = info['country']['iso_code']
KeyError: 'country'
```

I couldn't reproduce it: when I ran stig again and repeated what I'd done before, the peer list was shown as expected. Most likely the particular peer that caused stig to crash wasn't connected anymore.

Let me know if there's anything else I can do to help debug this. I kept the torrent file in case you need it.

I'm running stig 707642d on Xubuntu 18.04.

**Comment by rndusr** [comment]
Thanks for the detailed report.

It looks like you found an IP that maxminddb can't tie to a country. The latest
commit in master should handle this case more gracefully.

**Comment by marcelpaulo** [comment]
Great, thanks, @rndusr ! I've already pulled and installed it.
