### ISSUE TITLE
Cannot load theme from home

### ISSUE THREAD

**Issue by quite** [rndusr/stig#8]
I'm copying the default.theme to my home and and trying to set it like this
 
    set tui.theme /home/quite/.config/stig/my.theme

But end up getting this when starting:

```
Exception in callback _CommandBase.__init__.<locals>.<lambda>(<Task finishe...te 'theme'",)>) at /usr/lib/python3.6/site-packages/stig/commands/__init__.py:222
handle: <Handle _CommandBase.__init__.<locals>.<lambda>(<Task finishe...te 'theme'",)>) at /usr/lib/python3.6/site-packages/stig/commands/__init__.py:222>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/stig/tui/hooks.py", line 57, in _set_theme
    tui.theme.load(cfg['tui.theme'].value, tui.urwidscreen)
AttributeError: module 'stig.tui.main' has no attribute 'theme'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/site-packages/stig/commands/__init__.py", line 222, in <lambda>
    self._task.add_done_callback(lambda task: self._catch_exceptions(task.result))
  File "/usr/lib/python3.6/site-packages/stig/commands/__init__.py", line 241, in _catch_exceptions
    self._finish(success=False, exception=exc)
  File "/usr/lib/python3.6/site-packages/stig/commands/__init__.py", line 259, in _finish
    self.on_error(self.exception)
  File "/usr/lib/python3.6/site-packages/stig/commands/__init__.py", line 496, in handle_exc
    raise exc
  File "/usr/lib/python3.6/site-packages/stig/commands/__init__.py", line 229, in _catch_exceptions
    success = callabee(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/stig/commands/base/config.py", line 80, in run
    setting.set(val)
  File "/usr/lib/python3.6/site-packages/stig/settings/settings.py", line 121, in set
    self.__on_change.send(self)
  File "/usr/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/lib/python3.6/site-packages/stig/tui/hooks.py", line 58, in _set_theme
    except tui.theme.ThemeError as e:
AttributeError: module 'stig.tui.main' has no attribute 'theme'
```

**Comment by rndusr** [comment]
Thanks for the report. Should be fixed in master.

I'm not going to bother with a bugfix release because I'm planning to make a
new feature release in the next few days anyway.

**Comment by quite** [comment]
With the exact same setup, I now get
```
Exception in callback _CommandBase.__init__.<locals>.<lambda>(<Task finishe..._default()',)>) at /usr/lib/python3.6/site-packages/stig/commands/__init__.py:222
handle: <Handle _CommandBase.__init__.<locals>.<lambda>(<Task finishe..._default()',)>) at /usr/lib/python3.6/site-packages/stig/commands/__init__.py:222>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/site-packages/stig/commands/__init__.py", line 222, in <lambda>
    self._task.add_done_callback(lambda task: self._catch_exceptions(task.result))
  File "/usr/lib/python3.6/site-packages/stig/commands/__init__.py", line 241, in _catch_exceptions
    self._finish(success=False, exception=exc)
  File "/usr/lib/python3.6/site-packages/stig/commands/__init__.py", line 259, in _finish
    self.on_error(self.exception)
  File "/usr/lib/python3.6/site-packages/stig/commands/__init__.py", line 496, in handle_exc
    raise exc
```

**Comment by rndusr** [comment]
Sorry. Now it should work. Can you checkout master again and confirm?

**Comment by quite** [comment]
Yup, now we're good.

**Comment by rndusr** [comment]
Great. Thanks.
