### ISSUE TITLE
Option to remove torrents without confirmation, ignoring remove.max-hits

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#80]
It would be useful to have a command line option to `rm` that would remove torrents without any confirmation, no matter the value of `remove.max-hits`. This is essential for non-interactive scripts. `remove.max-hits` is essential for interactive use.

I have a maintenance script that removes stopped torrents. I found this on the systemd logs tonight:

```
jun 05 19:00:07 monk torr[28157]: Are you sure you want to remove 11 torrents and their files? [y|n] Traceback (most recent call last):
jun 05 19:00:07 monk torr[28157]:   File "/home/paulo/.local/bin/stig", line 11, in <module>
jun 05 19:00:07 monk torr[28157]:     load_entry_point('stig==0.9.0a0', 'console_scripts', 'stig')()
jun 05 19:00:07 monk torr[28157]:   File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/__init__.py", line 24, in run
jun 05 19:00:07 monk torr[28157]:     main.run()
jun 05 19:00:07 monk torr[28157]:   File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/main.py", line 178, in run
jun 05 19:00:07 monk torr[28157]:     if not run_commands():
jun 05 19:00:07 monk torr[28157]:   File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/main.py", line 155, in run_commands
jun 05 19:00:07 monk torr[28157]:     success = cmdmgr.run_sync(clicmds, on_error=log.error)
jun 05 19:00:07 monk torr[28157]:   File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/commands/__init__.py", line 576, in run_sync
jun 05 19:00:07 monk torr[28157]:     self._maybe_run_callbacks(process, on_success, on_error)
jun 05 19:00:07 monk torr[28157]:   File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/commands/__init__.py", line 529, in _maybe_run_callbacks
jun 05 19:00:07 monk torr[28157]:     raise exc
jun 05 19:00:07 monk torr[28157]:   File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/commands/__init__.py", line 243, in _catch_exceptions
jun 05 19:00:07 monk torr[28157]:     success = callabee(*args, **kwargs)
jun 05 19:00:07 monk torr[28157]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
jun 05 19:00:07 monk torr[28157]:     return future.result()
jun 05 19:00:07 monk torr[28157]:   File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/commands/__init__.py", line 243, in _catch_exceptions
jun 05 19:00:07 monk torr[28157]:     success = callabee(*args, **kwargs)
jun 05 19:00:07 monk torr[28157]:   File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/commands/base/torrent.py", line 228, in run
jun 05 19:00:07 monk torr[28157]:     after=self.remove_list_of_hits)
jun 05 19:00:07 monk torr[28157]:   File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/commands/cli/_mixin.py", line 69, in ask_yes_no
jun 05 19:00:07 monk torr[28157]:     key = await aiogetch(self.aioloop)
jun 05 19:00:07 monk torr[28157]:   File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/commands/cli/_mixin.py", line 54, in aiogetch
jun 05 19:00:07 monk torr[28157]:     old_settings = termios.tcgetattr(sys.stdin.fileno())
jun 05 19:00:08 monk torr[28157]: termios.error: (25, 'Inappropriate ioctl for device')
jun 05 19:00:08 monk torr[28157]: Unclosed client session
jun 05 19:00:08 monk torr[28157]: client_session: <aiohttp.client.ClientSession object at 0x7f6d379f9c50>
jun 05 19:00:08 monk torr[28157]: Unclosed connector
jun 05 19:00:08 monk torr[28157]: connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f6d3bf65278>, 152206.333649093)]']
jun 05 19:00:08 monk torr[28157]: connector: <aiohttp.connector.TCPConnector object at 0x7f6d379f9da0>
```

and then realized that `remove.max-hits` is 10, the default value, and there were 11 torrents to be deleted. I know I can work around it increasing `remove.max-hits`, which I've already done, but it does seem to me that it's safer to have a lower value for interactive usage, and no restrictions for non-interactive usage.

**Comment by rndusr** [comment]
I already had that on my TODO, but I hadn't thought about non-interactive
behaviour. I'm not sure if ignoring max-hits would be best in that case, but a
better error message is definitely necessary.

I'm planning to add a --force/-f switch that ignores max-hits. You can use that
in scripts and if you don't, you'll get an error message if user-confirmation
isn't possible.

**Comment by marcelpaulo** [comment]
The -f switch would be perfect.

**Comment by rndusr** [comment]
The `remove` command now has a `--force`/`-f` option that ignores the
`remove.max-hits` setting.

Also, if stdout is not a TTY, there is no user prompt and `remove` defaults to
'no' so torrents are not deleted if in doubt.

Soon, I'll make it possible to disable `remove.max-hits` altogether in case
someone never needs that extra safety feature and doesn't want to use `-f` all
the time.

**Comment by marcelpaulo** [comment]
Have just tested it, great, thanks ! Will revert my _rc_ file to the default and change my maintenance script to use `-f`.

You are in a commit spree today !
