### ISSUE TITLE
Crashing when running /comment on TUI: KeyError: 'comment'

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#95]
On the TUI, I ran **/**, currently bound to the default:

```
interactive 'limit "%s"' --per-change --on-cancel 'limit --clear' --ignore-errors
```

typed `comment`, and stig crashed:

```
Traceback (most recent call last):
  File "/home/paulo/.local/bin/stig", line 11, in <module>
    load_entry_point('stig==0.9.0a0', 'console_scripts', 'stig')()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/__init__.py", line 24, in run
    main.run()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/main.py", line 188, in run
    if not tui.run(run_commands):
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/main.py", line 193, in run
    urwidloop.run()
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/urwidpatches.py", line 170, in run
    raise self._exc_info
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 1443, in faux_idle_callback
    callback()
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 572, in entering_idle
    self.draw_screen()
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid/widget.py", line 1765, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid/container.py", line 1529, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/tabs.py", line 129, in render
    canvas = current_widget.render(size_content, focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/views/__init__.py", line 235, in render
    self._hide_or_unhide_widgets()
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/views/__init__.py", line 297, in _hide_or_unhide_widgets
    hidden_ids = tuple(w.id for w in self._limit_items(existing_widgets))
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/views/__init__.py", line 297, in <genexpr>
    hidden_ids = tuple(w.id for w in self._limit_items(existing_widgets))
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/tui/views/torrent_list.py", line 128, in _limit_items
    if not f.match(tw.data):
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/client/filters/__init__.py", line 400, in match
    for AND_chain in self._filterchains)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/client/filters/__init__.py", line 400, in <genexpr>
    for AND_chain in self._filterchains)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/client/filters/__init__.py", line 399, in <genexpr>
    return any(all(f.match(obj) for f in AND_chain)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/client/filters/__init__.py", line 281, in match
    return self._filter_func(obj) ^ self._invert
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/client/filters/__init__.py", line 239, in <lambda>
    self._filter_func = lambda obj, keys=f.needed_keys: all(bool(obj[key]) for key in keys)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/client/filters/__init__.py", line 239, in <genexpr>
    self._filter_func = lambda obj, keys=f.needed_keys: all(bool(obj[key]) for key in keys)
  File "/home/paulo/.local/lib/python3.6/site-packages/stig-0.9.0a0-py3.6.egg/stig/client/aiotransmission/torrent.py", line 503, in __getitem__
    value = raw[fields[0]]
KeyError: 'comment'
```

It was accidental: I meant to type a filter expression, `comment~monk`, but stig crashed after I finished typing `comment`.

Running latest master as of 2018/08/09 (cbf994e) on Xubuntu 18.04.1

**Comment by rndusr** [comment]
That was a sneaky one. Thanks! This bug probably would've stayed in the shadows
for a long time if you hadn't requested a filter for comments.

**Comment by marcelpaulo** [comment]
As it has always happened in science, accidents leading to discoveries !

I've just installed latest master, and the sneaky bug has been squashed dead !

Thanks !
