### ISSUE TITLE
Errors installing most recent from git.

### ISSUE THREAD

**Issue by DiagonalArg** [rndusr/stig#99]
I can install from the repos fine, but installing from git is failing.  Ubuntu 16.04.

```
~$ pip3 install --user 'git+https://github.com/rndusr/stig.git#egg=stig[geoip,setproctitle]'

Collecting stig[geoip,setproctitle] from git+https://github.com/rndusr/stig.git#egg=stig[geoip,setproctitle]
  Cloning https://github.com/rndusr/stig.git to /tmp/pip-build-xl_t_ucr/stig
Collecting urwid>=2.0 (from stig[geoip,setproctitle])
Collecting urwidtrees>=1.0.3dev0 (from stig[geoip,setproctitle])
Collecting aiohttp>=3 (from stig[geoip,setproctitle])
  Using cached https://files.pythonhosted.org/packages/70/c0/380f2bd0a6505998e984efd23b692afe662c4e27603f066c632eed7bf3ee/aiohttp-3.4.4-cp35-cp35m-manylinux1_x86_64.whl
Collecting async_timeout (from stig[geoip,setproctitle])
  Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting pyxdg (from stig[geoip,setproctitle])
  Using cached https://files.pythonhosted.org/packages/39/03/12eb9062f43adb94e30f366743cb5c83fd15fef026500cd4de42c7c12280/pyxdg-0.26-py2.py3-none-any.whl
Collecting blinker (from stig[geoip,setproctitle])
Collecting natsort (from stig[geoip,setproctitle])
  Using cached https://files.pythonhosted.org/packages/e3/31/b937f858addee2e1a62f15842f0f3f07e9277aa87fb67fe9b9e28ac90d50/natsort-5.4.1-py2.py3-none-any.whl
Collecting maxminddb (from stig[geoip,setproctitle])
Collecting setproctitle (from stig[geoip,setproctitle])
Collecting mock (from urwidtrees>=1.0.3dev0->stig[geoip,setproctitle])
  Using cached https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp>=3->stig[geoip,setproctitle])
  Using cached https://files.pythonhosted.org/packages/67/9b/8075ec8f51df63c09afcce59ddb325d57e4d0a3c03db794c9d58f7a1ca4f/yarl-1.2.6-cp35-cp35m-manylinux1_x86_64.whl
Collecting idna-ssl>=1.0; python_version < "3.7" (from aiohttp>=3->stig[geoip,setproctitle])
Collecting multidict<5.0,>=4.0 (from aiohttp>=3->stig[geoip,setproctitle])
  Using cached https://files.pythonhosted.org/packages/13/fb/c354524db72408c60f9044b81491f0f3bac9d315279177ae51f4cfb340b5/multidict-4.4.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting chardet<4.0,>=2.0 (from aiohttp>=3->stig[geoip,setproctitle])
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting attrs>=17.3.0 (from aiohttp>=3->stig[geoip,setproctitle])
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock->urwidtrees>=1.0.3dev0->stig[geoip,setproctitle])
  Using cached https://files.pythonhosted.org/packages/ca/81/4e8230c5648ea6d85d90ec3babc3dcc1c46d890f2f26b3e2b374819274dd/pbr-5.0.0-py2.py3-none-any.whl
Collecting six>=1.9 (from mock->urwidtrees>=1.0.3dev0->stig[geoip,setproctitle])
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp>=3->stig[geoip,setproctitle])
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Installing collected packages: urwid, pbr, six, mock, urwidtrees, idna, multidict, yarl, idna-ssl, async-timeout, chardet, attrs, aiohttp, pyxdg, blinker, natsort, maxminddb, setproctitle, stig
  Running setup.py install for stig ... done
Successfully installed aiohttp-3.4.0 async-timeout-1.2.1 attrs-18.1.0 blinker-1.4 chardet-3.0.3 idna-2.7 idna-ssl-1.1.0 maxminddb-1.4.1 mock-2.0.0 multidict-4.3.1 natsort-5.3.3 pbr-3.0.1 pyxdg-0
.26 setproctitle-1.1.10 six-1.10.0 stig-0.10.1a0 urwid-1.3.1 urwidtrees-1.0.3.dev0 yarl-1.2.6
```

```
~$ stig
Traceback (most recent call last):
  File "/home/me/.local/bin/stig", line 9, in <module>
    load_entry_point('stig==0.10.1a0', 'console_scripts', 'stig')()
  File "/home/me/.local/lib/python3.5/site-packages/stig/__init__.py", line 18, in run
    from . import main
  File "/home/me/.local/lib/python3.5/site-packages/stig/main.py", line 34, in <module>
    from .singletons import (aioloop, log, localcfg, remotecfg, srvapi, helpmgr,
  File "/home/me/.local/lib/python3.5/site-packages/stig/singletons.py", line 25, in <module>
    from . import settings
  File "/home/me/.local/lib/python3.5/site-packages/stig/settings/__init__.py", line 15, in <module>
    from .defaults import init_defaults
  File "/home/me/.local/lib/python3.5/site-packages/stig/settings/defaults.py", line 22, in <module>
    from ..client.sorters.torrent import TorrentSorter
  File "/home/me/.local/lib/python3.5/site-packages/stig/client/__init__.py", line 20, in <module>
    from .filters import (TorrentFilter, TorrentFileFilter, TorrentPeerFilter,
  File "/home/me/.local/lib/python3.5/site-packages/stig/client/filters/__init__.py", line 12, in <module>
    from .torrent import TorrentFilter
  File "/home/me/.local/lib/python3.5/site-packages/stig/client/filters/torrent.py", line 18, in <module>
    from .utils import (timestamp_or_timedelta, time_filter, limit_rate_filter)
  File "/home/me/.local/lib/python3.5/site-packages/stig/client/filters/utils.py", line 12, in <module>
    from ..ttypes import (Timedelta, Timestamp)
  File "/home/me/.local/lib/python3.5/site-packages/stig/client/ttypes.py", line 536, in <module>
    from . import base
  File "/home/me/.local/lib/python3.5/site-packages/stig/client/base.py", line 73
    parts = [f'xt=urn:btih:%s' % t['hash']]
                             ^
SyntaxError: invalid syntax
```

**Comment by rndusr** [comment]
Thanks for reporting a bug.

Should be fixed now.

**Comment by DiagonalArg** [comment]
Wow, that was quick!  :)
